<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-12-11T11:08:49+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Berlin',
];
