<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-12-11T11:15:04+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.4',
    'version_db_installed' => '20200609145307',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1607681328,
        'do_page_reindex_check' => false,
    ],
];
